import { DUMMY_ID } from '@/config/constants';
import { routes } from '@/config/routes';
import {
  PiAirplaneTiltDuotone,
  PiApplePodcastsLogoDuotone,
  PiArrowsOutDuotone,
  PiArrowsOutLineHorizontalDuotone,
  PiBellSimpleRingingDuotone,
  PiBinocularsDuotone,
  PiBriefcaseDuotone,
  PiBrowserDuotone,
  PiCalendarDuotone,
  PiCalendarPlusDuotone,
  PiCaretCircleUpDownDuotone,
  PiChartBarDuotone,
  PiChartLineUpDuotone,
  PiChartPieSliceDuotone,
  PiChatCenteredDotsDuotone,
  PiClipboardTextDuotone,
  PiCodesandboxLogoDuotone,
  PiCoinDuotone,
  PiContactlessPayment,
  PiCreditCardDuotone,
  PiCurrencyCircleDollarDuotone,
  PiCurrencyDollarDuotone,
  PiEnvelopeDuotone,
  PiEnvelopeSimpleOpenDuotone,
  PiFeatherDuotone,
  PiFlagBanner,
  PiFolderDuotone,
  PiFolderLockDuotone,
  PiFoldersDuotone,
  PiFolderUserDuotone,
  PiGridFourDuotone,
  PiHammerDuotone,
  PiHeadsetDuotone,
  PiHourglassSimpleDuotone,
  PiHouseLineDuotone,
  PiListNumbersDuotone,
  PiLockKeyDuotone,
  PiMapPinLineDuotone,
  PiMoneyDuotone,
  PiNewspaperClippingDuotone,
  PiNoteBlankDuotone,
  PiPackageDuotone,
  PiPresentationChartDuotone,
  PiPushPinDuotone,
  PiRocketLaunchDuotone,
  PiScalesDuotone,
  PiShapesDuotone,
  PiShieldCheckDuotone,
  PiShootingStarDuotone,
  PiShoppingCartDuotone,
  PiSparkleDuotone,
  PiSquaresFourDuotone,
  PiStairsDuotone,
  PiStepsDuotone,
  PiTableDuotone,
  PiUserCircleDuotone,
  PiUserDuotone,
  PiUserGearDuotone,
  PiUserPlusDuotone,
  PiTruckDuotone,
} from 'react-icons/pi';
import { GoHome, GoPeople } from 'react-icons/go';
import { MdOutlineCampaign, MdOutlineSell, MdPayments } from 'react-icons/md';
import { IoReturnDownBack } from 'react-icons/io5';
// Note: do not add href in the label object, it is rendering as label
export const menuItems = [
  // label start
  {
    name: 'Overview',
  },
  {
    name: 'Home',
    href: '/',
    icon: <GoHome />,
    permission: { resource: [], action: '*' },
  },
  {
    name: 'Products',
    href: routes.eCommerce.products,
    icon: <PiPackageDuotone />,
    permission: { resource: ['products'], action: 'read' },
  },
  {
    name: 'Categories',
    href: routes.eCommerce.categories,
    icon: <PiSquaresFourDuotone />,
    permission: { resource: ['categories'], action: 'read' },
  },
  {
    name: 'Returns',
    href: routes.eCommerce.returns,
    icon: <IoReturnDownBack />,
    permission: { resource: ['orders'], action: 'read' },
  },
  {
    name: 'Reviews',
    icon: <GoPeople />,
    href: '#',
    permission: { resource: ['reviews'], action: 'read' },
    dropdownItems: [
      {
        name: 'All reviews',
        href: routes.eCommerce.reviews,
      },
      {
        name: 'Reviews by Product',
        href: routes.eCommerce.reviewsByProduct,
      },
      {
        name: 'Reviews by User',
        href: routes.eCommerce.reviewsByUser,
      },
    ],
  },
  {
    name: 'Coupons',
    href: routes.eCommerce.coupons,
    icon: <PiNewspaperClippingDuotone />,
    permission: { resource: ['coupons'], action: 'read' },
  },
  {
    name: 'Banner',
    href: routes.eCommerce.banners,
    icon: <PiFlagBanner />,
    permission: { resource: ['banners'], action: 'read' },
  },
  {
    name: 'Sale',
    href: routes.eCommerce.flashSales,
    icon: <MdOutlineSell />,
    permission: { resource: ['sales'], action: 'read' },
  },
  {
    name: 'Campaign',
    href: routes.eCommerce.campaign,
    icon: <MdOutlineCampaign />,
    permission: { resource: ['campaigns'], action: 'read' },
  },
  {
    name: 'Users',
    href: routes.users.list,
    icon: <PiUserDuotone />,
    permission: { resource: ['users'], action: 'read' },
  },
  {
    name: 'Orders',
    href: routes.eCommerce.orders,
    icon: <PiShoppingCartDuotone />,
    permission: { resource: ['orders'], action: 'read' },
  },
  {
    name: 'Transactions',
    href: routes.transactions.list,
    icon: <PiMoneyDuotone />,
    permission: { resource: ['transactions'], action: 'read' },
  },
  {
    name: 'Analytics',
    href: '#',
    icon: <PiChartLineUpDuotone />,
    permission: { resource: ['analytics'], action: 'read' },
    dropdownItems: [
      {
        name: 'Sales',
        href: '/analytics/sales',
      },
      {
        name: 'Orders',
        href: '/analytics/orders',
      },
      {
        name: 'Transactions',
        href: '/analytics/transactions',
      },
      {
        name: 'Users',
        href: '/analytics/users',
      },
      {
        name: 'Products',
        href: '/analytics/products',
      },
      {
        name: 'Reviews',
        href: '/analytics/reviews',
      },
      {
        name: 'Coupons',
        href: '/analytics/coupons',
      },
    ],
  },
  {
    name: 'Logistics',
    href: routes.eCommerce.logistics.home,
    icon: <PiPackageDuotone />,
    permission: { resource: ['logistics'], action: 'read' },
  },
  {
    name: 'Shipment',
    href: routes.eCommerce.shipment.dashboard,
    icon: <PiAirplaneTiltDuotone />,
    permission: { resource: ['logistics'], action: 'read' },
  },
  {
    name: 'Delivery',
    href: routes.eCommerce.delivery.list,
    icon: <PiTruckDuotone />,
    permission: { resource: ['delivery'], action: 'read' },
  },
  {
    name: 'Invoice',
    href: routes.invoice,
    icon: <PiCurrencyDollarDuotone />,
    permission: { resource: ['invoices'], action: 'read' },
  },
  {
    name: 'Account Settings',
    href: routes.forms.profileSettings,
    icon: <PiUserGearDuotone />,
    permission: { resource: ['*'], action: '*' },
  },
  {
    name: 'Roles & Permissions',
    href: routes.rolesPermissions,
    icon: <PiFolderLockDuotone />,
    permission: { resource: ['roles'], action: 'read' },
  },
  {
    name: 'Store Settings',
    href: routes.jobBoard.dashboard,
    icon: <PiShapesDuotone />,
  },
];
